name: 'publish to slack'
description: 'ya publish to slack'

inputs:
  slack_token:  # id of input
    required: true
  slack_channel: 
    required: true
  slack_color:
    required: true
  slack_title:
    required: true
  slack_message:
    required: true
    
runs:
  using: "composite"
  steps:
    - shell: bash
      id: set_payload
      env:
        SLACK_CHANNEL: ${{ inputs.slack_channel }}
        SLACK_COLOR: ${{ inputs.slack_color }}
        SLACK_TITLE: ${{ inputs.slack_title }}
        SLACK_MESSAGE: ${{ inputs.slack_message }}
      run: |
        SLACK_MESSAGE=`sed -e 's/^"//' -e 's/"$//' <<<"$SLACK_MESSAGE"`
        echo $SLACK_MESSAGE
        SLACK_MESSAGE="Nothing"
        echo $SLACK_MESSAGE
        jsonMessage=`cat ./.github/actions/slack-publish/slack_format.json`
        jsonMessage=`echo $jsonMessage | envsubst` 
        jsonMessage=`echo $jsonMessage | tr '\n' ' '`
        echo $jsonMessage
        echo "::set-output name=payload::$jsonMessage"
    - shell: bash
      run: |
        ./.github/actions/slack-publish/slack_send.sh '${{ inputs.slack_token }}' '${{ steps.set_payload.outputs.payload }}'
