name: 'publish to slack'
description: 'ya publish to slack'

inputs:
  slack_token:  # id of input
    required: true
    
runs:
  using: "composite"
  steps:
    - shell: bash
      id: set_payload
      run: |
        jsonMessage=`cat ./.github/actions/slack-publish/slack_test2.json`
        jsonMessage=$(printf "%q" $jsonMessage)
        echo $jsonMessage
        echo "::set-output name=payload::$jsonMessage"
    - shell: bash
      run: |
        ./.github/actions/slack-publish/slack_send.sh '${{ inputs.slack_token }}' "${{ steps.set_payload.outputs.payload }}"
