name: 'publish to slack'
description: 'ya publish to slack'

runs:
  using: "composite"
  steps:
    - shell: bash
      id: set_payload
      run: |
        jsonMessage=`cat ./.github/actions/slack-publish/slack_test2.json`
        jsonMessage="${jsonMessage//'%'/'%25'}"
        jsonMessage="${jsonMessage//$'\n'/'%0A'}"
        jsonMessage="${jsonMessage//$'\r'/'%0D'}"
        echo "::set-output name=payload::$jsonMessage"
    - shell: bash
      run: |
        curl -X POST https://slack.com/api/chat.postMessage -d  "${{ toJson(steps.set_payload.outputs.payload) }}" -H "Authorization: Bearer $secrets.SLACK_TOKEN" -H "Content-Type: application/json"
