name: 'publish to slack'
description: 'ya publish to slack'

runs:
  using: "composite"
  steps:
    - shell: bash
      id: set_payload
      run: |
        jsonMessage=`cat ./.github/actions/slack-publish/slack_format.json`
        jsonMessage="${jsonMessage//'%'/'%25'}"
        jsonMessage="${jsonMessage//$'\n'/'%0A'}"
        jsonMessage="${jsonMessage//$'\r'/'%0D'}"
        echo "::set-output name=payload::$jsonMessage"
    - shell: bash
      run: |
        echo "${{fromJson(steps.set_payload.outputs.payload).text.attachments[0].author_name}}"
