name: 'publish to slack'
description: 'ya publish to slack'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        ls ./.github/actions/slack-publish
        jsonMessage=$(< ./.github/actions/slack-publish/slack_format.json)
        payload=$(printf '%s' "$jsonMessage" | jq --raw-input --slurp '.')
        echo "$payload"
