name: 'publish to slack'
description: 'ya publish to slack'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        ls
        jsonMessage=$(< ./slack_format.json)
        payload=$(printf '%s' "$jsonMessage" | jq --raw-input --slurp '.')
        curl -X POST https://slack.com/api/chat.postMessage -d  "${{ toJSON($payload) }}" -H "Authorization: Bearer ${secrets.SLACK_TOKEN}"
