name: 'publish to slack'
description: 'ya publish to slack'



runs:
  using: "composite"
  steps:
    - shell: bash
      id: set_payload
      run: |
        jsonMessage=`cat ./.github/actions/slack-publish/slack_test2.json`
        echo "::set-output name=payload::$jsonMessage"
    - name: send-to-slack
      env:
        SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
      run: |
        ./.github/actions/slack-publish/slack_send.sh '${{steps.set_payload.outputs.payload }}'
